# app.py
"""
POINT BLANK — Single-page iOS-style Dark Streamlit app
- Yahoo Finance data
- Indicators: MA20, MA50, EMA, RSI, MACD, Bollinger Bands
- Forecasts: Prophet, ARIMA, Random Forest, LSTM
- Recent News display with time and date
"""

import warnings
warnings.filterwarnings("ignore")

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import timedelta, datetime, timezone

# --------------------------
# ML libraries
# --------------------------
HAS_PROPHET = False
HAS_ARIMA = False
HAS_SKLEARN = False
HAS_TF = False

try:
    from prophet import Prophet
    HAS_PROPHET = True
except:
    Prophet = None

try:
    from statsmodels.tsa.arima.model import ARIMA
    HAS_ARIMA = True
except:
    ARIMA = None

try:
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.preprocessing import MinMaxScaler
    HAS_SKLEARN = True
except:
    RandomForestRegressor = None
    MinMaxScaler = None

try:
    import tensorflow as tf
    from tensorflow import keras
    from tensorflow.keras import layers
    HAS_TF = True
except:
    tf = None
    keras = None
    layers = None

# --------------------------
# Streamlit page config + CSS
# --------------------------
st.set_page_config(page_title="POINT.BLANK", layout="wide")

st.markdown("""
<style>
body, .stApp {background-color: #000000; color: #E6E6E6; font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Display', Roboto, sans-serif;}
.block-container {padding-top: 1.5rem; max-width: 1150px; margin-left:auto; margin-right:auto;}
.stButton>button {background-color: #1C1C1E; color: #E6E6E6; border-radius: 12px; border: 1px solid #2C2C2E; padding: 0.55em 1em;}
.stTextInput>div>div>input, .stSelectbox>div>div, .stSlider>div>div {background-color: #0F0F10; color: #E6E6E6; border-radius: 10px; border: 1px solid #222224;}
.stCheckbox>div, .stRadio>div {color: #E6E6E6;}
h1, h2, h3, h4 {color: #E6E6E6; text-align: center;}
.model-availability {background-color:#0B0B0C; padding:8px; border-radius:8px; border:1px solid #202022;}
.news-card {background-color:#0F0F10; border:1px solid #2C2C2E; border-radius:12px; padding:12px; margin-bottom:10px;}
.news-title {font-weight:600; color:#E6E6E6;}
.news-meta {font-size:12px; color:#9E9E9E; margin-top:2px;}
a {color:#4DA6FF; text-decoration:none;}
a:hover {text-decoration:underline;}
</style>
""", unsafe_allow_html=True)

# --------------------------
# Disclaimer Gate
# --------------------------
st.markdown("## ⚠️ Disclaimer")
st.markdown("""
Point blank provides stock market data, analysis, and predictive tools for **educational and informational purposes only**.  

- Point blank does **not** provide financial, investment, trading, or legal advice.  
- All information, forecasts, and analytics generated by Point blank are **estimates only** and may be inaccurate, incomplete, or outdated.  
- Stock market investments are inherently **risky and volatile**. Past performance is not indicative of future results.  
- Users are solely responsible for any investment or trading decisions made based on Point blank’s content.  
- The developers, owners, affiliates, and contributors of Point blanck shall **not be held liable** for any financial losses, damages, or consequences arising directly or indirectly from its use.  

By using Point blanck, you acknowledge that you understand these risks and agree to use Point blanck at your own discretion and responsibility.  
For personalized financial guidance, please consult a licensed financial advisor.
""")

accept = st.checkbox(" I have read and accept the disclaimer")

if not accept:
    st.warning("⚠️ Please accept the disclaimer to use Point blank.")
    st.stop()

# --------------------------
# Utilities
# --------------------------
@st.cache_data(ttl=300)
def fetch_yahoo_data(ticker: str, period="6mo", interval="1d") -> pd.DataFrame:
    try:
        t = yf.Ticker(ticker)
        df = t.history(period=period, interval=interval)
        if df is None or df.empty:
            return pd.DataFrame()
        df = df.reset_index()
        df['Date'] = pd.to_datetime(df['Date']).dt.tz_localize(None)
        for col in ['Open','High','Low','Close','Volume']:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors='coerce')
        df = df.dropna(subset=['Date','Close']).reset_index(drop=True)
        return df
    except Exception:
        return pd.DataFrame()

def fetch_news(ticker: str, max_items: int = 5):
    try:
        t = yf.Ticker(ticker)
        news = t.news if hasattr(t, "news") else []
        items = []
        for n in news[:max_items]:
            ts = n.get("providerPublishTime", None)
            dt = datetime.fromtimestamp(ts, tz=timezone.utc).astimezone() if ts else None
            rel_time = dt.strftime("%Y-%m-%d %H:%M") if dt else ""
            items.append({
                "title": n.get("title", ""),
                "link": n.get("link", ""),
                "publisher": n.get("publisher", ""),
                "time": rel_time
            })
        return items
    except Exception:
        return []

def compute_indicators(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy().reset_index(drop=True)
    df['MA20'] = df['Close'].rolling(20).mean()
    df['MA50'] = df['Close'].rolling(50).mean()
    df['EMA12'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['EMA26'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = df['EMA12'] - df['EMA26']
    df['Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['BB_MID'] = df['Close'].rolling(20).mean()
    df['BB_STD'] = df['Close'].rolling(20).std(ddof=0).fillna(0)
    df['BB_UP'] = df['BB_MID'] + 2*df['BB_STD']
    df['BB_LOW'] = df['BB_MID'] - 2*df['BB_STD']
    delta = df['Close'].diff()
    up = delta.clip(lower=0)
    down = -delta.clip(upper=0)
    roll_up = up.rolling(14).mean()
    roll_down = down.rolling(14).mean()
    rs = roll_up / (roll_down + 1e-8)
    df['RSI'] = 100 - (100 / (1 + rs))
    df['RSI'] = df['RSI'].clip(0,100).fillna(50)
    return df

def plot_advanced(df: pd.DataFrame, title: str, show_indicators: bool = True):
    fig = make_subplots(rows=3, cols=1, shared_xaxes=True,
                        row_heights=[0.6,0.18,0.22],
                        vertical_spacing=0.03)
    fig.add_trace(go.Candlestick(x=df['Date'], open=df['Open'], high=df['High'],
                                 low=df['Low'], close=df['Close'], name='Price'), row=1, col=1)
    if show_indicators:
        fig.add_trace(go.Scatter(x=df['Date'], y=df['MA20'], name='MA20', line=dict(width=1.4)), row=1, col=1)
        fig.add_trace(go.Scatter(x=df['Date'], y=df['MA50'], name='MA50', line=dict(width=1.4, dash='dash')), row=1, col=1)
        fig.add_trace(go.Scatter(x=df['Date'], y=df['BB_UP'], name='BB_UP', line=dict(width=1, dash='dot')), row=1, col=1)
        fig.add_trace(go.Scatter(x=df['Date'], y=df['BB_LOW'], name='BB_LOW', line=dict(width=1, dash='dot')), row=1, col=1)
    fig.add_trace(go.Bar(x=df['Date'], y=df['Volume'], name='Volume', marker_color='gray', opacity=0.3), row=2, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['RSI'], name='RSI', line=dict(width=1.2)), row=3, col=1)
    fig.add_hline(y=70, line_dash='dot', row=3, col=1)
    fig.add_hline(y=30, line_dash='dot', row=3, col=1)
    fig.update_layout(template='plotly_dark', title=title,
                      margin=dict(l=20,r=20,t=40,b=10),
                      paper_bgcolor='#000000', plot_bgcolor='#000000',
                      legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1))
    st.plotly_chart(fig, use_container_width=True, theme=None)

# --------------------------
# Main UI
# --------------------------
st.title("POINT BLANK")

tickers_list = [
    "AAPL","MSFT","GOOG","AMZN","TSLA","META","NVDA","JPM","V","JNJ","WMT",
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS","SBIN.NS",
    "BTC-USD","ETH-USD"
]

controls = st.columns([2,2,2,2,1])
with controls[0]:
    ticker = st.selectbox("Ticker", tickers_list, index=0)
with controls[1]:
    period = st.selectbox("History period", ["1mo","3mo","6mo","1y","2y","5y","10y","max"], index=2)
with controls[2]:
    interval = st.selectbox("Interval", ["1d","1wk","1mo"], index=0)
with controls[3]:
    show_indicators = st.checkbox("Show Indicators", value=True)
with controls[4]:
    run = st.button("Run All")

st.markdown("---")

if run:
    df = fetch_yahoo_data(ticker, period, interval)
    if df.empty:
        st.error("No data retrieved. Check ticker or network.")
        st.stop()
    df = compute_indicators(df)

    last = df.iloc[-1]
    cols = st.columns([1,1,1,1,1])
    with cols[0]: st.metric("Date", str(pd.to_datetime(last['Date']).date()))
    with cols[1]: st.metric("Open", f"{last['Open']:.2f}")
    with cols[2]: st.metric("High", f"{last['High']:.2f}")
    with cols[3]: st.metric("Low", f"{last['Low']:.2f}")
    with cols[4]: st.metric("Close", f"{last['Close']:.2f}")

    plot_advanced(df, f"{ticker} — Price & Indicators", show_indicators)

    st.download_button("Download raw data (CSV)", df.to_csv(index=False), file_name=f"{ticker}_raw.csv", mime="text/csv")

    # NEWS SECTION
    st.subheader("📰 Recent News")
    news_items = fetch_news(ticker)
    if not news_items:
        st.info("No recent news available for this stock.")
    else:
        for n in news_items:
            st.markdown(f"""
            <div class="news-card">
                <div class="news-title"><a href="{n['link']}" target="_blank">{n['title']}</a></div>
                <div class="news-meta">{n['publisher']} • {n['time']}</div>
            </div>
            """, unsafe_allow_html=True)

    st.markdown("---")
    st.subheader("Recent data (tail)")
    st.dataframe(df.tail(50), use_container_width=True)
else:
    st.info("Select ticker and press 'Run All' to fetch data, forecasts, and news.")
